# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploying docs

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            NEXT_PUBLIC_BASE_PATH: /juki-svelte
            HOST: https://paakofiaidoo.github.io

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install packages
              run: yarn install
            - name: Build project
              run: yarn build-storybook
            # - name: Export static files
            #   run: yarn export
            # - name: Add .nojekyll file
            #   run: touch ./docs/.nojekyll

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@4.1.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages # The branch the action should deploy to.
                  FOLDER: docs # The folder the action should deploy.
